# *******************************************************************************
# Copyright (c) 2023 BMW AG
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
#   See the NOTICE file(s) distributed with this work for additional
#   information regarding copyright ownership.
#
#   This program and the accompanying materials are made available under the
#   terms of the Apache License, Version 2.0 which is available at
#   https://www.apache.org/licenses/LICENSE-2.0.
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#
#   SPDX-License-Identifier: Apache-2.0
#   ********************************************************************************

postgres:
  enabled: true
  auth:
    password: &psqlPassword "psql_password"
    username: &psqlUsername "postgresql_sandbox_user"
    database: edc
  persistence:
    enabled: true

txdc:
  postgresql:
    enabled: true
    jdbcUrl: "jdbc:postgresql://txdc-postgres:5432/edc"
    username: *psqlUsername
    password: *psqlPassword
  vault:
    hashicorp:
      enabled: true
      url: "https://vault.demo.catena-x.net"
      healthCheck:
        enabled: true
        standbyOk: true

  backendService:
    httpProxyTokenReceiverUrl: "http://txdc-backend"
  serviceAccount:
    create: false

  participant:
    id: "BPNL00DEMAND0001"

  controlplane:
    ssi:
      miw:
        # -- MIW URL
        url: "https://managed-identity-wallets-new.int.demo.catena-x.net"
        # -- The BPN of the issuer authority
        authorityId: "BPNL00DEMAND0001"
      oauth:
        # -- The URL (of KeyCloak), where access tokens can be obtained
        tokenurl: "https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
        client:
          # -- The client ID for KeyCloak
          id: "sa631"
          # -- The alias under which the client secret is stored in the vault.
          secretAlias: "value-added-service/dcm/dev/client"

opensearch:
  enabled: true
  replicas: 1
  protocol: http
  roles:
    - master
    - ingest
    - data
  resources:
    limits:
      cpu: 300m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 2Gi
  config:
    opensearch.yml: |
      cluster.name: opensearch-cluster
      # Bind to all interfaces because we don't know what
      # IP address Docker will assign to us.
      network.host: 0.0.0.0
      # Disable security
      plugins.security.disabled: true
  securityConfig:
    enabled: false
  extraInitContainers:
    # Image that performs the sysctl operation to modify Kernel settings
    # needed sometimes to avoid boot errors
    - name: sysctl
      image: docker.io/bitnami/bitnami-shell:10-debian-10-r199
      imagePullPolicy: "IfNotPresent"
      command:
        - /bin/bash
        - -ec
        - |
          CURRENT=`sysctl -n vm.max_map_count`;
          DESIRED="262144";
          if [ "$DESIRED" -gt "$CURRENT" ]; then
              sysctl -w vm.max_map_count=262144;
          fi;
          CURRENT=`sysctl -n fs.file-max`;
          DESIRED="65536";
          if [ "$DESIRED" -gt "$CURRENT" ]; then
              sysctl -w fs.file-max=65536;
          fi;
      securityContext:
        runAsUser: 0
        privileged: true