name: Veracode Static Analysis Pipeline Scan

on:
  push:
    branches: [ "feature/DCMFOSS-61" ]
    paths:
      - 'demand-capacity-mgmt-frontend/**'
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '27 12 * * 6'

permissions:
  contents: read

jobs:
  analyse-frontend:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write


    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3
        with:
          repository: ''

      - name: Zip Project
      - run: zip -r veracode-scan-target.zip ./

      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.4
        with:
          appname: "demand-capacity-mgmt-frontend"
          createprofile: false
          filepath: "./veracode-scan-target.zip"
          vid: "${{ secrets.VERACODE_API_ID }}"
          vkey: "${{ secrets.VERACODE_API_KEY }}"